dataset_name: 'scannet'
camera_params:
  image_height: 1440
  image_width: 1920
  fx: 0.0  # To be loaded from the instrinsic files in ScanNet dataset
  fy: 0.0
  cx: 0.0
  cy: 0.0
  png_depth_scale: 1000.0 #for depth image in png format
